# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Item.create(name:"", description:"", price:, picture:"")

Item.create(name:"Nike Roshe One", description:"Simplicity at its finest. The upper is made of a mix of lightweight and very breathable materials. Full-length Phylon midsole with a Solarsoft sockliner supplies premium comfort. The Phylon outsole with a Waffle®-inspired design makes for excellent traction.", price:74.99, picture:"http://images.footlocker.com/is/image//EBFL/11881432_fr_nike_sc7?hei=500&wid=500")
Item.create(name:"Jordan AJ XX9", description:"Performance-woven, single-piece upper excludes excess layering. Four layers provide the athlete with everything they need: comfort, support, strength, and protection. Articulate padding lines in the collar help prevent the heel from slipping inside the shoe. Flight Web fit system uses webbed straps that wrap the foot and integrate with the laces through woven channels in the upper for midfoot lockdown.", price:159.99, picture:"http://images.footlocker.com/is/image//EBFL/95515023_fr_ven_sc7?hei=500&wid=500")
Item.create(name:"Nike Flyknit 3", description:"Nike Flyknit upper is breathable, stretchy, and supportive for the perfect fit. An integrated tongue stays firmly in place while you run. Plush collar huge your heel while a contoured sockliner supports your foot from underneath. Lunarlon foam midsole provides responsive cushioning. Pressure-mapped outsole with flex grooves encourages natural motion and comfort.", price:149.99, picture:"http://images.footlocker.com/is/image//EBFL/98181010_fr_sc7?hei=500&wid=500")
Item.create(name:"Nike Free 5.0", description:"A combination of sandwich mesh and dynamic Flywire technology in the upper creates a breathable feel and a secure fit. Phylon midsole features flex grooves that allow your foot to move naturally through the gait cycle. A new flex pattern in the outsole allows six directions of motion for extreme flexibility. Strategically placed rubber lugs lend durability where you need it most.", price:99.99, picture:"http://images.footlocker.com/is/image//EBFL/24382003_fr_sc7?hei=500&wid=500")
Item.create(name:"Adidas Adipower", description:"Strong Structure Chassis is weightlifting-engineered. Low-cut PU-coated leather upper adds durability while air mesh offers breathability. Lightweight EVA midsole for cushioning. Single instep strap delivers additional rearfoot integrity that helps secure your feet. Heel support design focuses on an integral rearfoot to add superb, lightweight stability.", price:149.99, picture:"http://images.footlocker.com/is/image//EBFL/25733_fr_nike_sc7?hei=500&wid=500")
Item.create(name:"Timberland Classic", description:"Crafted for comfort, with a design that's stylish and durable. Premium, hand-sewn nubuck and suede upper. 360º functional lacing creates a customized fit. Siped rubber outsole gives maximum traction.", price:94.99, picture:"http://images.footlocker.com/is/image//EBFL/25077_fr_sc7_rootbear?hei=500&wid=500")
Item.create(name:"Timberland Kempton", description:"Premium full-grain leather upper with water repellency makes for comfort and long-lasting wear. 100% organic cotton laces. TPR welt for a premium look. EVA midsole for all-day cushioning and shock absorption. SensorFlex technology delivers underfoot support, independent suspension, and greater flexibility for the ultimate smooth ride over any terrain.", price:79.99, picture:"http://images.footlocker.com/is/image//EBFL/9227B484_fr_timberland_sc7?hei=500&wid=500")
Item.create(name:"Puma El Harbor", description:"The PUMA El Harbor is a fresh take on the iconic El Ace. The nylon/canvas upper is inspired by on-trend men's dress shoes for a unique, eye-catching look, and the molded rubber strap and rubber outsole give this classy shoe a sense of laid-back style.", price:53.99, picture:"http://images.footlocker.com/is/image//EBFL/35787903_fr_puma_sc7?hei=500&wid=500")
